### ISSUE TITLE
OSError: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by leewi9** [FirefighterBlu3/python-pam#18]
```
202.120.235.2 - - [14/Nov/2019 16:05:15] "GET /reset/u18210980089/123456/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/_project/jupyterhub_password_manager/back/back.py", line 17, in reset_password
    rst = p.authenticate(name_str, password_str)
  File "/opt/anaconda3/envs/jupyterhub_py_3_7_5/lib/python3.7/site-packages/pam.py", line 178, in authenticate
    ctty = os.environ.get('DISPLAY', os.ttyname(0)).encode(encoding)
OSError: [Errno 25] Inappropriate ioctl for device
202.120.235.2 - - [14/Nov/2019 16:05:20] "GET /reset/u18210980089/123456/123 HTTP/1.1" 500 -
```

flask code
```
@app.route('/reset/<name_str>/<password_str>/<new_password_str>')
def reset_password(name_str, password_str, new_password_str):
    #
    try:
        #
        p = pam.pam()
        rst = p.authenticate(name_str, password_str)
        #
        if rst:
            #
            os.system('echo %s:%s | sudo /usr/sbin/chpasswd ' % (name_str, new_password_str))
            #
            return 'success'
        else:
            return 'incorrect password'
    except Exception as e:
        return str(e)


if __name__ == '__main__':
    #
    app.run(host='0.0.0.0', port=6000)
    #
```

please help, don't know how to fix this, thank you.

**Comment by FirefighterBlu3** [comment]
hrm. that's unfortunate, let me see what I can do

**Comment by FirefighterBlu3** [comment]
does commit 013da9d (develop branch) fix your problem?

**Comment by leewi9** [comment]
this is my workaround

```
        # if X DISPLAY is set, use it, otherwise get the STDIN tty
        # ctty = os.environ.get('DISPLAY', os.ttyname(0)).encode(encoding)
        ctty = 'STDIN'.encode(encoding)
        ctty = c_char_p(ctty)
```

**Comment by FirefighterBlu3** [comment]
that's a valid but entirely arbitrary string which doesn't represent a real TTY. did you try my patch?
