### ISSUE TITLE
Is `six` a missing dependency somehow?

### ISSUE THREAD

**Issue by pmorch** [FirefighterBlu3/python-pam#41]
Hi, I can see that `six` does seem to already [be a dependency](https://github.com/FirefighterBlu3/python-pam/blame/master/pyproject.toml#L5) (something I don't really understand), but it seems to still be missing from 2.0.2:

```
$ mkdir /tmp/venv

$ cd /tmp/venv

$ python3 -m venv .

$ ./bin/pip install python-pam
Collecting python-pam
  Using cached python_pam-2.0.2-py3-none-any.whl (10 kB)
Installing collected packages: python-pam
Successfully installed python-pam-2.0.2

$ ./bin/python -c 'import pam ; print("hi")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.11/site-packages/pam/__init__.py", line 9, in <module>
    from .__internals import PAM_ACCT_EXPIRED
  File "/tmp/venv/lib/python3.11/site-packages/pam/__internals.py", line 2, in <module>
    import six
ModuleNotFoundError: No module named 'six'

$ ./bin/pip install six
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six
Successfully installed six-1.16.0

$ ./bin/python -c 'import pam ; print("hi")'
hi
```

**Comment by svmhdvn** [comment]
I'm running into this issue too, @FirefighterBlu3 would you be able to take a look? Working around this by manually installing this locally for now.

**Comment by FirefighterBlu3** [comment]
My apologies, let me fix that up

**Comment by pkoning2** [comment]
It's still broken in the published version 2.0.2.

**Comment by FirefighterBlu3** [comment]
thank you all, six is gone now
